curl -s -o .vscode/settings.json --create-dirs "https://raw.githubusercontent.com/ymkz/template-config/main/.vscode/settings.json"
curl -s -O "https://raw.githubusercontent.com/ymkz/template-config/main/.editorconfig"
curl -s -O "https://raw.githubusercontent.com/ymkz/template-config/main/.prettierignore"
curl -s -O "https://raw.githubusercontent.com/ymkz/template-config/main/.prettierrc.cjs"
curl -s -O "https://raw.githubusercontent.com/ymkz/template-config/main/tsconfig.json"
